### ISSUE TITLE
No log file was produced

### ISSUE THREAD

**Issue by gxjyj** [MultiBUGS/MultiBUGS#51] opened 2020-06-10 23:00 UTC
dear Dr:
when I run my code by R2MultiBUGS, it shows error that"MultiBUGS did not run correctly. No log file was produced.". How can I do for the error? thank you!

**Comment by rjbgoudie** [comment] 2020-09-15 19:12
Duplicate of https://github.com/MultiBUGS/R2MultiBUGS/issues/8

**Closed by rjbgoudie** 2020-09-15 19:12 UTC
